### ISSUE TITLE
Portable version instead of requiring installer

### ISSUE THREAD

**Issue by moshen** [ryangriggs/PDFEncrypt#1]
What the title says

**Comment by ryangriggs** [comment]
@moshen You can just extract the compressed contents of the installer into a folder using a ZIP app like 7-zip, and run PDFEncrypt.exe.  There's no need for installation except to create icons.  When I get time, I'll create a portable ZIP file download.  Thanks for the feedback.

You can also install onto one PC, then simply copy everything in the installation folder to the destination PC(s).

**Comment by moshen** [comment]
Nice! Thanks. I was looking at adding this to https://github.com/ScoopInstaller/Extras , it would also help if you had release versions, but that doesn't appear to be strictly necessary.

**Comment by ryangriggs** [comment]
@moshen Unfortunately I've only released one version at this point.  Will hopefully set up versioning soon as v2 is completely updated.
