### ISSUE TITLE
Add instructions on how to build and run the application

### ISSUE THREAD

**Issue by mjarosie** [ryangriggs/PDFEncrypt#5]
That'd be great for someone new to the project so that it's easier to start contributing. Ideally that'd include running a dockerised version of the application so that the required setup is minimal.

**Comment by ryangriggs** [comment]
This app is built in Windows using Visual Studio. Can we dockerize that platform?
It's simple to build the app by just downloading the code from Github and opening the project with Visual Studio.  Not sure we need the extra work of creating and maintaining a docker container for this environment. 
Your thoughts?

**Comment by mjarosie** [comment]
Yeah I just realised as I was setting up my environment (I'm not working with .net on a daily basis). It was as simple as installing the most recent version of Visual Studio and selecting .NET Framework 4.7.2 developer pack during the installation. That specific .NET Framework version requirement could perhaps still be mentioned?

**Comment by ryangriggs** [comment]
I added the build instructions to the Readme.
